# use node as a parent image
FROM node:10

# set the working directory
# WORKDIR /app

# copy the current directory contents into app folder
# COPY . /app

# install elasticdump using npm
RUN npm install -g elasticdump