# use python as a parent image
FROM node:10

# set the workind directory
# WORKDIR /app

# copy the current directory contents into app folder
# COPY . /app

# install packages from requirements
RUN npm install -g elasticdump